name: pull_request

on:
  pull_request:
    branches:
      - master

jobs:
  pull-request:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Lint Action
      uses: samuelmeuli/lint-action@v1.2.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        eslint: true
    - name: Run unit tests
      run: npm test
      env:
        CI: true
